<?php

use App\taxcondition;
use App\Taxoperation;
use App\Taxdocuments;
use Illuminate\Database\Seeder;

class AfipTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        taxcondition::truncate();

        $item = new taxcondition();
        $item->description = 'IVA Responsable Inscripto';
        $item->save();
        $item = new taxcondition();
        $item->description = 'IVA Responsable no Inscripto';
        $item->save();
        $item = new taxcondition();
        $item->description = 'IVA no Responsable';
        $item->save();
        $item = new taxcondition();
        $item->description = 'IVA Sujeto Exento';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Consumidor Final';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Responsable Monotributo';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Sujeto no Categorizado';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Proveedor del Exterior';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Cliente del Exterior';
        $item->save();
        $item = new taxcondition();
        $item->description = 'IVA Liberado – Ley Nº 19.640';
        $item->save();
        $item = new taxcondition();
        $item->description = 'IVA Responsable Inscripto – Agente de Percepción';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Pequeño Contribuyente Eventual';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Monotributista Social';
        $item->save();
        $item = new taxcondition();
        $item->description = 'Pequeño Contribuyente Eventual Social';
        $item->save();

        Taxoperation::truncate();
        Taxoperation::unguard();

        $item = new Taxoperation();
        $item->id = 0;
        $item->value = 0;
        $item->description = 'No Corresponde';
        $item->save();
        $item = new Taxoperation();
        $item->id = 1;
        $item->value = 0;
        $item->description = 'No Gravado';
        $item->save();
        $item = new Taxoperation();
        $item->id = 2;
        $item->value = 0;
        $item->description = 'Exento';
        $item->save();
        $item = new Taxoperation();
        $item->id = 3;
        $item->value = 0;
        $item->description = '0%';
        $item->save();
        $item = new Taxoperation();
        $item->id = 4;
        $item->value = 10.5;
        $item->description = '10,50%';
        $item->save();
        $item = new Taxoperation();
        $item->id = 5;
        $item->value = 21;
        $item->description = '21%';
        $item->save();
        $item = new Taxoperation();
        $item->id = 6;
        $item->value = 27;
        $item->description = '27%';
        $item->save();
        $item = new Taxoperation();
        $item->id = 7;
        $item->value = 0;
        $item->description = 'Gravado';
        $item->save();
        $item = new Taxoperation();
        $item->id = 8;
        $item->value = 5;
        $item->description = '5%';
        $item->save();
        $item = new Taxoperation();
        $item->id = 9;
        $item->value = 2.5;
        $item->description = '2,50%';
        $item->save();

        Taxdocuments::Truncate();
        Taxdocuments::unguard();

        $item = new Taxdocuments();
        $item->id = "001";
        $item->description = "FACTURAS A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "002";
        $item->description = "NOTAS DE DEBITO A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "003";
        $item->description = "NOTAS DE CREDITO A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "004";
        $item->description = "RECIBOS A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "005";
        $item->description = "NOTAS DE VENTA AL CONTADO A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "006";
        $item->description = "FACTURAS B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "007";
        $item->description = "NOTAS DE DEBITO B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "008";
        $item->description = "NOTAS DE CREDITO B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "009";
        $item->description = "RECIBOS B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "010";
        $item->description = "NOTAS DE VENTA AL CONTADO B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "011";
        $item->description = "FACTURAS C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "012";
        $item->description = "NOTAS DE DEBITO C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "013";
        $item->description = "NOTAS DE CREDITO C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "015";
        $item->description = "RECIBOS C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "016";
        $item->description = "NOTAS DE VENTA AL CONTADO C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "017";
        $item->description = "LIQUIDACION DE SERVICIOS PUBLICOS CLASE A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "018";
        $item->description = "LIQUIDACION DE SERVICIOS PUBLICOS CLASE B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "019";
        $item->description = "FACTURAS DE EXPORTACION";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "020";
        $item->description = "NOTAS DE DEBITO POR OPERACIONES CON EL EXTERIOR";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "021";
        $item->description = "NOTAS DE CREDITO POR OPERACIONES CON EL EXTERIOR";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "022";
        $item->description = "FACTURAS - PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "023";
        $item->description = "COMPROBANTES “A” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "024";
        $item->description = "COMPROBANTES “A” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "025";
        $item->description = "COMPROBANTES “B” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "026";
        $item->description = "COMPROBANTES “B” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "027";
        $item->description = "LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "028";
        $item->description = "LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "029";
        $item->description = "LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "030";
        $item->description = "COMPROBANTES DE COMPRA DE BIENES USADOS";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "031";
        $item->description = "MANDATO - CONSIGNACION";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "032";
        $item->description = "COMPROBANTES PARA RECICLAR MATERIALES";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "033";
        $item->description = "LIQUIDACION PRIMARIA DE GRANOS";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "034";
        $item->description = "COMPROBANTES A DEL APARTADO A  INCISO F)  R.G. N°  1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "035";
        $item->description = "COMPROBANTES B DEL ANEXO I, APARTADO A, INC. F), R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "036";
        $item->description = "COMPROBANTES C DEL Anexo I, Apartado A, INC.F), R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "037";
        $item->description = "NOTAS DE DEBITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "038";
        $item->description = "NOTAS DE CREDITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "039";
        $item->description = "OTROS COMPROBANTES A QUE CUMPLEN CON LA R G  1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "040";
        $item->description = "OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "041";
        $item->description = "OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "043";
        $item->description = "NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "044";
        $item->description = "NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "045";
        $item->description = "NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "046";
        $item->description = "NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "047";
        $item->description = "NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "048";
        $item->description = "NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "049";
        $item->description = "COMPROBANTES DE COMPRA DE BIENES NO REGISTRABLES A CONSUMIDORES FINALES";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "050";
        $item->description = "RECIBO FACTURA A  REGIMEN DE FACTURA DE CREDITO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "051";
        $item->description = "FACTURAS M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "052";
        $item->description = "NOTAS DE DEBITO M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "053";
        $item->description = "NOTAS DE CREDITO M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "054";
        $item->description = "RECIBOS M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "055";
        $item->description = "NOTAS DE VENTA AL CONTADO M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "056";
        $item->description = "COMPROBANTES M DEL ANEXO I  APARTADO A  INC F) R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "057";
        $item->description = "OTROS COMPROBANTES M QUE CUMPLAN CON LA R.G. N° 1415";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "058";
        $item->description = "CUENTAS DE VENTA Y LIQUIDO PRODUCTO M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "059";
        $item->description = "LIQUIDACIONES M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "060";
        $item->description = "CUENTAS DE VENTA Y LIQUIDO PRODUCTO A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "061";
        $item->description = "CUENTAS DE VENTA Y LIQUIDO PRODUCTO B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "063";
        $item->description = "LIQUIDACIONES A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "064";
        $item->description = "LIQUIDACIONES B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "066";
        $item->description = "DESPACHO DE IMPORTACION";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "068";
        $item->description = "LIQUIDACION C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "070";
        $item->description = "RECIBOS FACTURA DE CREDITO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "080";
        $item->description = "INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "081";
        $item->description = "TIQUE FACTURA A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "082";
        $item->description = "TIQUE FACTURA B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "083";
        $item->description = "TIQUE";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "088";
        $item->description = "REMITO ELECTRONICO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "089";
        $item->description = "RESUMEN DE DATOS";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "090";
        $item->description = "OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE CREDITO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "091";
        $item->description = "REMITOS R";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "099";
        $item->description = "OTROS COMPROBANTES QUE NO CUMPLEN O ESTÁN EXCEPTUADOS DE LA R.G. 1415 Y SUS MODIF";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "110";
        $item->description = "TIQUE NOTA DE CREDITO";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "111";
        $item->description = "TIQUE FACTURA C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "112";
        $item->description = "TIQUE NOTA DE CREDITO A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "113";
        $item->description = "TIQUE NOTA DE CREDITO B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "114";
        $item->description = "TIQUE NOTA DE CREDITO C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "115";
        $item->description = "TIQUE NOTA DE DEBITO A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "116";
        $item->description = "TIQUE NOTA DE DEBITO B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "117";
        $item->description = "TIQUE NOTA DE DEBITO C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "118";
        $item->description = "TIQUE FACTURA M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "119";
        $item->description = "TIQUE NOTA DE CREDITO M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "120";
        $item->description = "TIQUE NOTA DE DEBITO M";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "201";
        $item->description = "FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "202";
        $item->description = "NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "203";
        $item->description = "NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) A";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "206";
        $item->description = "FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "207";
        $item->description = "NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "208";
        $item->description = "NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) B";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "211";
        $item->description = "FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "212";
        $item->description = "NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "213";
        $item->description = "NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) C";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "331";
        $item->description = "LIQUIDACION SECUNDARIA DE GRANOS";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "332";
        $item->description = "CERTIFICACION ELECTRONICA (GRANOS)";
        $item->order = 999;
        $item->save();
        $item = new Taxdocuments();
        $item->id = "995";
        $item->description = "REMITO ELECTRÓNICO CÁRNICO";
        $item->order = 999;
        $item->save();
    }
}
